---
- name: WinRM precheck (minimo, sin colecciones, estable)
  hosts: localhost
  gather_facts: false

  vars:
    win_host: "{{ ansible_host | default(inventory_hostname) }}"

  tasks:
    - name: Runner hostname (via python)
      ansible.builtin.command:
        argv:
          - python3
          - -c
          - "import socket; print(socket.gethostname())"
      register: r_host
      changed_when: false
      delegate_to: localhost
      run_once: true
      failed_when: false

    - name: Runner src IPv4 hacia el Windows (best-effort, via python)
      ansible.builtin.command:
        argv:
          - python3
          - -c
          - "import socket; s=socket.socket(socket.AF_INET, socket.SOCK_DGRAM); s.connect(('{{ win_host }}',1)); print(s.getsockname()[0]); s.close()"
      register: r_src_ip
      changed_when: false
      delegate_to: localhost
      run_once: true
      failed_when: false

    - name: TCP check 5985 (WinRM HTTP) desde el runner
      ansible.builtin.wait_for:
        host: "{{ win_host }}"
        port: 5985
        timeout: 3
        state: started
      delegate_to: localhost
      register: tcp_5985
      failed_when: false

    - name: TCP check 5986 (WinRM HTTPS) desde el runner
      ansible.builtin.wait_for:
        host: "{{ win_host }}"
        port: 5986
        timeout: 3
        state: started
      delegate_to: localhost
      register: tcp_5986
      failed_when: false

    - name: Resumen
      ansible.builtin.debug:
        msg:
          runner_hostname: "{{ r_host.stdout | default('UNKNOWN') }}"
          runner_src_ip_to_target: "{{ r_src_ip.stdout | default('UNKNOWN') }}"
          target: "{{ inventory_hostname }}"
          target_addr: "{{ win_host }}"
          tcp_5985_open: "{{ (tcp_5985.failed is not defined) or (not tcp_5985.failed) }}"
          tcp_5986_open: "{{ (tcp_5986.failed is not defined) or (not tcp_5986.failed) }}"
